import './globals.css';

import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ConfigStoreProvider } from '~/stores/config/config-store-provider';
import { TimerStoreProvider } from '~/stores/timer/timer-store-provider';
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({ // <-- Initialize GeistMono
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geistMono.variable}`}>
      <body>
        <ConfigStoreProvider>
          <TimerStoreProvider>
            {children}
          </TimerStoreProvider>
        </ConfigStoreProvider></body>
    </html>
  );
}
